---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "telemt"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemt
  template:
    metadata:
      labels:
        app: telemt
    spec:
      containers:
      - name: telemt
        image: ghcr.io/telemt/telemt:3.4.25@sha256:acca0ec53323c9f91469c10a982691c94573d720a89a04fe005b57675316ed65
        command: ["/app/telemt"]
        args: ["/etc/telemt/config.toml"]
        ports:
          - name: https
            containerPort: 443
          - name: metrics
            containerPort: 9090
          - name: api
            containerPort: 9091
        envFrom:
          - configMapRef:
              name: "telemt-env"
        livenessProbe:
          exec:
            command:
            - "/app/telemt"
            - "healthcheck"
            - "/etc/telemt/config.toml"
            - "--mode"
            - "liveness"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        volumeMounts:
          - name: "telemt"
            mountPath: "/etc/telemt"
            readOnly: true
      volumes:
        - name: "telemt"
          secret:
            secretName: "telemt"
