apiVersion: v1
kind: Secret
metadata:
    name: telemt
    namespace: ntc
type: Opaque
stringData:
    config.toml: ENC[AES256_GCM,data:dOHo1WXtxdQL7TpG9QB6onbdaUj9wJD/zNra4EaDb0cS1gTxlQxLzjOtCXMCA5VnJF4GfeJf5hbGIm+gg5U4z87akAL82NgK5q34oXx4oYe553a9Bje/BigxbOO6upi9Di9FT6Sqp7FaHR0b+xATqs4Q3SZSqEIkTaoZOltGmZW3DMkj6A0+eUCKfv6b3cPb+Dzo/OTfoGEs2ARdbYAKJKAwpR40Ut5ScwxMVYEfcySlIE92BRYbBNeuhswzssVVYvoYwb4Z4Ji2hG4wY1Kb9XyyROQ8hmrnMBLa8j28e6snh2srQoSvzBxmlDOZsZstyLbKC3KegbcPdQeNaNFAPD5YyIKwGZVcpFrgquUPDhumsk500jH6hx1Q0849aTOr6LgNAeAM2as1Z1a7JNCkUiAyqxnNnfH3RvsLdXUZlSPFNAwDHJ3kuiezMbhEp07in0sgjT2TQQaLgPiIf8Hds06u4VI94VfJmnF8KFXa+hjUFNBSaclW/BUSDa49qp4Opr4945ncoOlg5UH6taktMmNSVjHmI3bc7v1vrGU+wuBVT0zdmKrjlblJwrlSSgs0mcP9uVGVa7ZRRXR++Ud4QaUrhuDRDMqPt+R7kVMf7sTHIE54HA6SHSyDM5SEdU8IEQDrnR1QWXcV1Hy+R9NGs6vgb9bdb1yJxaez7frI+I6luJ/+UK1Q4OZxdSRSQChMtbDewBVtphQNVF5u+mr2PSS50Xryen5kbRLzgMTFw9mBNrkqYL+1vP8Ac3jTxuxJdRQ/NorjalFaO+gI5W5vtPKqQGhvPiL6IpCWVnuM3TNaplAbgVgR16ZZ3c/ydZcunwI+sQECG1NqKaqm+q2UE1lpS91+jNOuM9kcq7nXkeW2I/cyngC2lJX5Aan071ilFqejiJ2vvjV5xWGy7TX2s26Xr35qu6MykM+61mNCl9ahCV+Aotf7LswyvLRIrdzh2eZM3tgpTJpHWOpnky5rRQao5b3IFVUpcD9eSICpu1zpqlXVM4MPsi1JIx443heFlOC1guMsfa2uHjVsjxmkFS1469077V5ZfWOrCIDy3Dj8TPGNvw9oTZWrrd1AAzhiT1KLltFM6U95TI7k6TryYp+B0uakg7kpX/cuMOUZzfytWQziXC1hjIz99xxthhR50pLjgPg9gHncIoNSO96iY9ZAheEW4yRdDfePp4umZH3RdmFCEbt8K/ieW465P+5KFyyt,iv:hCCGZmohr3hfZCX4pFAE+lEM0OfP8+XbQVlFuqU6bSE=,tag:oi2ARJDMzsn5MsM+mFWHLg==,type:str]
sops:
    age:
        - recipient: age1yjgkfwawgzy5qf45jhjz4f49zjp0zntw6xj4mggw8ehjed0w9u2qxqahvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRHFRNEF6QmlwdFh0Tko5
            UGJJMk5LS2VLK21vcUJtcWJCNVQwWFhsTEFJCk9JNVpGZTNPVzJCZGJFQzZ6RFA4
            d050a0VaL1FkSVdTTldBays4NFdqanMKLS0tIDd2UG5tenlOLzczQjJiQ3VLUko4
            L204VVloK0UvalFHUC9DWHRJRkpOZlkKJdT2zRvB4G5A+IQeV4n0M0qrSroPh+D6
            KqgQoHjI/fkIC+jKA4u6Xhcc9qwTvdqNGEGe4Ze7Q1YhDkttba12SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T08:14:43Z"
    mac: ENC[AES256_GCM,data:VpDhGCr3uS1b8A0KkrBo3tN7nM/X4G8jdt9MpYcHM30779nGUhw8++tfblRzRcfKYhMtL3miNraM+FgjgoC4V2AkUjx9inb4yz5I1XwY/0h0ZwTYAJJlZaGTn0HwnlTpVAybk4iW71/GqdTXhT9XieV9tQVDIIjDHcTw5Y/w86M=,iv:7Fy9kb4HA9x92EmBGucfrxlwtXc1JqraNs3GrD12TJs=,tag:SCne4rwYaTHCAhDoTakinw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
