---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: "postgresql-bitmagnet"
spec:
  teamId: "bitmagnet"
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 3072Mi
  volume:
    size: 20Gi
    storageClass: "openebs-seagate-barracuda-2tb-pool"
  numberOfInstances: 1
  users:
    postgres:
    - superuser
    - createdb
    bitmagnet: []
  databases:
    bitmagnet: bitmagnet
  postgresql:
    version: "17"
