---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mount-part
  namespace: mount-part
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mount-part
  template:
    metadata:
      labels:
        app: mount-part
    spec:
      hostPID: true
      containers:
      - name: alpine
        image: alpine:3.20.3
        command: ["/mount.sh"]
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "CAP_SYS_ADMIN"]
          allowPrivilegeEscalation: true
        volumeMounts:
          - name: dev
            mountPath: "/dev"
          - name: var
            mountPath: "/var/mount-part"
          - name: mount-script
            mountPath: /mount.sh
            subPath: mount.sh
      volumes:
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: var
          hostPath:
            path: /var/mount-part
            type: DirectoryOrCreate
        - name: mount-script
          configMap:
            name: mount-script
            defaultMode: 0755
