---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zfdash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-zfs-kingston
