apiVersion: v1
kind: Secret
metadata:
    name: tuya-web
stringData:
    config.yaml: ENC[AES256_GCM,data:WwVFmLBCsPpEhYYd3giYPiDypvWLFJ8hRhxGcyS7IpyW6ARTBKpi8vVrg72oyWV/0BxQ2zrTnYPbyvMvk1aeT8Z0sPb+SHMQdm2cDV8z68tgNBM+fin9CujrmMFBH1v2NeKgLUHywO8uc9ERguesxHiiAgyoAhv9y+nRzlqVzjoqUMc5m9/JHmmfUQ==,iv:kicNNLTp30mYFAftDX6Fa6I24sfgTCpxMOsB9ElS/6Q=,tag:6pR2L8BTn0kT2QKLbU1TEw==,type:str]
sops:
    age:
        - recipient: age1yjgkfwawgzy5qf45jhjz4f49zjp0zntw6xj4mggw8ehjed0w9u2qxqahvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhekJraUN2Smxta1pNejVu
            VkdIb1lBN1ZHdEtUR2xaOE0vM0hHU3FjMVRJCnR1QnRqQklsZGh3VmFqTUNkdVdG
            WTVFVURSUGJIbzF6R3ArdHY4MEtPZ1EKLS0tIG9LQTI1RmFXcHlQWnVrWHMzeVpr
            RG5RbTRaSmdMV1lJbVVpT3lsdVZkc2MKj+7z68adgdMXn/E+4/PVUvVO0uOoJ1ys
            QFMqkbRLDB3IGBvYgeebccSjClwj/U2+gdBGU+E1arcJ4ng6fuEtGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T07:56:42Z"
    mac: ENC[AES256_GCM,data:lG8mrFNHPyj2zxc9aGzlVfTIHBHDatoQrEtLcbuyXmy1ywyWBnDgG+rGxB3QCnyCTxDNF3C9EZQkrgSxwbKYFrpK/g7WEK2jWJnDd/3qCZXDHAjLaWo976iTYJ6fsd4TLBj4T6OXhqBx5QxH4rUYHg0wb8YsENgKNkgnEhTplUc=,iv:w7bdYUWo8pO+GiRXgbFMhsaM8RQx5qLuwgl9CwxYKp4=,tag:Ear+eb5Cdb7hMCsLI+p1CQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
