---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: lan
spec:
  # TODO: возможно, в routes надо добавить default gw
  # https://github.com/Diaoul/home-ops/blob/main/kubernetes/apps/network/multus/networks/vpn.yaml
  #               {"dst": "192.168.88.0/24", "gw": "192.168.88.1"}
  # talosctl get links
  # TODO: сетевой интерфейс (ключ master) может поменять своё имя. Надо зафиксировать
  config: |-
    {
      "cniVersion": "1.1.0",
      "name": "lan",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp3s0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {"dst": "192.168.88.0/24", "gw": "192.168.88.1"}
            ]
          }
        }
      ]
    }
