---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seagate-barracuda-2tb-pool-torrent-pv
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  storageClassName: openebs-seagate-barracuda-2tb-pool
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: zfs.csi.openebs.io
    volumeHandle: torrent # Это название dataset
    fsType: zfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - anaconda
