---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: seagate-barracuda-2tb-pool-torrent-pvc
spec:
  storageClassName: openebs-seagate-barracuda-2tb-pool
  volumeName: seagate-barracuda-2tb-pool-torrent-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
