---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: seagate-barracuda-2tb-pool-torrent-pvc
spec:
  storageClassName: openebs-seagate-barracuda-2tb-pool
  volumeName: seagate-barracuda-2tb-pool-torrent-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pool-data-data-pvc
spec:
  storageClassName: openebs-pool-data
  volumeName: pool-data-data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3300Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pool-data-data-extended-pvc
spec:
  storageClassName: openebs-pool-data
  volumeName: pool-data-data-extended-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
