apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:kYzQoJPI5HMhdyrJAsf7Yhcdino5S1dIWVKJPzDdUAWqsrfGhy23wrKUE5n/1Ujh12RtHBw=,iv:MtMA4yG5w9zH7WMRfY0l58pCUZ7pHfyQm8BBPGPf3Uw=,tag:p+r3jYPEQC3zRUIt7UPzWg==,type:str]
sops:
    age:
        - recipient: age1yjgkfwawgzy5qf45jhjz4f49zjp0zntw6xj4mggw8ehjed0w9u2qxqahvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaEdvdHY1OThUU1lnTFly
            S2s4eDVxN3RkbjYvYUxDUTZLUVZCa1dFbVY0CnVMMmJDb0lxaFE2ME05MFZtMnh1
            eGQ3blFWOXR5OWpkZk1tbitSS2s2eDQKLS0tIDdFRi9LaEpFTk9WeXVPaFNWeFdq
            bHBKS3VkTmFkSmorRXF0RmhEUWQ5Mm8KCBhKOLNsr2bG83CpraB2NLauMwsOtOkE
            CgQClVQux9AYDGTxz11oy2uZryxymwLmr6+osndtTQV8pH4HZ+G2Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T12:23:49Z"
    mac: ENC[AES256_GCM,data:l++ukEzAqyVtf8uWXgqs1cauHoPiurYHgwL7PrabD+No1j8IfzgfqC/TOrZhQ8ypkFJnuYI3E5n9p12Q3GUVM5+PUaB5fJ7bG4nG9w6fxtvS+8XUUQdg5cHywY72OhjcwktSf/e62wlB4TZhytwQ51Vd2Ncjd3KaBZqQ1uKYXXo=,iv:28IrwaZv0MKYjahLmxwGT6Xh8FzfHKBqb6ytto1VQ3k=,tag:PJiijTYbG4n4MkGV2Lysxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
