# TODO: переделать нормально
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
stringData:
  admin-user: "admin"
  admin-password: "aite8ze8woih7aedeePoo9choovaig"
