---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "nfs-pool-data-pvc"
spec:
  volumeName: "nfs-pool-data-pv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: nfs
