---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-cm
  namespace: postgresql
data:
  postgresql.conf: |    
    listen_addresses = '*'
    max_connections = 20    
    shared_buffers = 256MB
    effective_cache_size = 768MB
    maintenance_work_mem = 64MB
    work_mem = 6553kB
    dynamic_shared_memory_type = posix
    max_wal_size = 1GB
    min_wal_size = 80MB  
    log_min_messages = info
    log_min_error_statement = debug5
    log_timezone = 'UTC'
    datestyle = 'iso, mdy'
    timezone = 'UTC'
    lc_messages = 'en_US.utf8'
    lc_monetary = 'en_US.utf8'
    lc_numeric = 'en_US.utf8'
    lc_time = 'en_US.utf8'
    default_text_search_config = 'pg_catalog.english'
