---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-claim
  namespace: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-zfs-kingston
