---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: postgresql
spec:
  type: ClusterIP
  ports:
  - name: psql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgresql
