apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Qhc79i0TCJlmNITKuFjDLVpvY9twFVGlxwIy9nVXTGQHrTV4ydR/tu2dE77O/UjFllqOJ9IyXEnX8KYgyDU042WvnW9fOyE4R6S9eElISxbT,iv:T2kdp/G0iho5tzyiGGH4xW/yMHwFgkJar77gQGhEcYg=,tag:uNulKnXB8Gv+bZtFZ4naEQ==,type:str]
    #ENC[AES256_GCM,data:oru3s6pJc1VzGW4Km8whSWrDkgutJWKZbf53,iv:1Zzbx0570aBXScbrzcPRHXIOcBBLMLvcxhavtKFfvUc=,tag:uiCtS2pKThy7UCqjYkgLmw==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:kL8X1uXHdrEzxaDpZQ==,iv:tPIos7+GnTmuJX18iTsVHYmWTM8CxjMLdVuRYu27HNc=,tag:gMAaGyyXE55efKv5QdwaFw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:++LMDxeUvrfqeYany3wkzT0l4l97QiJANw==,iv:GPM7BHjXExLPsGlttYXtKXRc5FZtrX+13HJqRPLi5Hs=,tag:OsfJ4g67FkR7DNaOevyzKw==,type:str]
sops:
    age:
        - recipient: age1yjgkfwawgzy5qf45jhjz4f49zjp0zntw6xj4mggw8ehjed0w9u2qxqahvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SVpVaTd4YmlUaENuRzJt
            ZHBibGFOU2RNNFc5YThwVGhaTmRMNmhObWdBCktWd1B6c1FFek9XdjlHMmFKVUph
            TUNlZHZnRGFIcXJLRm9xMDJQdGtUUzAKLS0tIGFwUUZMT3hqNHlKclZTV0ZIN0RW
            emRsbE44LzV1Z2pwaE5uT3NMUG05SDQKEB2+j0Y0s3nJ3gmjkhoIh+bzGOsYfvA3
            1VDhiNw1HePghvypL06M6f4eh7q8auypGLLFiduTK22UUCMdL5Igow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T06:00:27Z"
    mac: ENC[AES256_GCM,data:2alDS8rAYfVfApVF9frJFuPRCMHj04SfR7jwOOLpq48eOPsNezAY4pdLn9hFlwZZ4mtROPM+NB+PhGgfVAFQqLXk8GywrOhr6SGQLwU+aGvJT9ippNzuufv7Z/Nyf9HZ+ogslBlzbgLh5VZn+cTc1gj60tL2tY/yJqF0Q9lIEq4=,iv:/hzFpTCmRYLei+6JnMiWZjCcBtCoAd2+/Ikhid4i99U=,tag:TL4tw+MzxqxY1Bs8I9plUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
