---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuya-smartplug-exporter
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: tuya-smartplug-exporter
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: rkosegi
        namespace: flux-system
      interval: 30m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    config:
    - name: "plug-anaconda"
      id: "bf57c81de8fb7a06a6mzwh"
      key: "QB/LqrwlCkHl#Zm;"
      ip: "192.168.88.205"
