---
apiVersion: v1
kind: Service
metadata:
  name: naive
  namespace: ntc
spec:
  type: ClusterIP
  selector:
    app: naive
  ports:
    - name: "socks"
      protocol: TCP
      port: 1080
      targetPort: 1080
    - name: "http"
      protocol: TCP
      port: 8080
      targetPort: 8080
