---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuya-web
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuya-web
  template:
    metadata:
      labels:
        app: tuya-web
    spec:
      containers:
      - name: tuya-web
        image: ghcr.io/mistikan/tuya-web:edge@sha256:c94c7f43d8423df539028fae4ba91e38749133ea579410883b975886daecce4e
        imagePullPolicy: IfNotPresent
        # TODO: не хочет считывать, надо переделывать и дорабатывать конфиг
        args:
          - "/usr/src/app/tuya-web"
          - "-n"
          - "plug-anaconda"
          - "-d"
          - "${TUYA_ID}"
          - "-k"
          - "${TUYA_KEY}"
          - "-a"
          - "192.168.88.205"
          - "-p"
          - "3.4"
        env:
          - name: "RUST_LOG"
            value: "warn"
        envFrom:
          - secretRef:
              name: tuya-web
        ports:
          - containerPort: 3000
            name: metrics
            protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
