---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuya-web
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuya-web
  template:
    metadata:
      labels:
        app: tuya-web
    spec:
      containers:
      - name: tuya-web
        image: ghcr.io/mistikan/tuya-web@sha256:8cdd1340b4a61403392c4a59e0566dd42de789e55bd33724c265b9d9137cf545
        imagePullPolicy: IfNotPresent
        args:
          - "/usr/src/app/tuya-web"
          - "--config"
          - "/data/config.yaml"
        env:
          - name: "RUST_LOG"
            value: "warn"
        envFrom:
          - secretRef:
              name: tuya-web
        ports:
          - containerPort: 3000
            name: metrics
            protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
          - name: tuya-web
            mountPath: /data
      volumes:
        - name: tuya-web
          secret:
            secretName: tuya-web
