apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: monitoring
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: tuya-web
