---
apiVersion: v1
kind: Service
metadata:
  name: tuya-web
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: tuya-web
