---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tuya-web
  namespace: monitoring
  # TODO: не работает
spec:
  selector:
    matchLabels:
      app: tuya-web
  endpoints:
    - interval: 30s
      port: metrics
