---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-zfs-kingston
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: seagate-barracuda-2tb-pool-torrent-pvc
spec:
  storageClassName: openebs-seagate-barracuda-2tb-pool
  volumeName: seagate-barracuda-2tb-pool-torrent-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seagate-barracuda-2tb-pool-torrent-pv
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-seagate-barracuda-2tb-pool
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: zfs.csi.openebs.io
    volumeHandle: torrent # Это название dataset
    fsType: zfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - anaconda
