apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:vDu+neTwSBfiNOzKgn1LDwrubzrO4nvr+h0mt/MzLCKC2bIzXTXHkCpMXE+tMqnyXWU2LDOlqhDs1Oy70jHkApjjx87WNinpoF2+Sgs+wOG3m2DJPqrNMlru6crjmNAUez62OBT+7YcOr+rZk33xeZqSop0j/0rGPX5MRzphVdHs38OIHAnDAdvaFIrUuFcbJEwX23+gBJqM5sZx7Koq6jUDsZW8QaBZbZcF+ZEzzM1Ut0Ct,iv:+s9R/Lt/4GtNd33AXWn30lOU7alD7Dv5BAFO6zMy1ZM=,tag:lpXP+E2fxxNiMqmdRKDVRg==,type:str]
sops:
    age:
        - recipient: age1yjgkfwawgzy5qf45jhjz4f49zjp0zntw6xj4mggw8ehjed0w9u2qxqahvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VURZZVpXMmZJOHo5UWNX
            bUc0TTU4ck5IOTBaNDJpdEIzQ0FkR3ZpZ0Q4CmZla1VNSS92VXVnS2o0eW1tSWY1
            SCtOUGFHZGgwalN5MEJjS0dYbUN2bjgKLS0tIDEzKy9pTnR2NUh5NVJOcElLc2F6
            QW5oTy84OEJIeFE5N1Q1VzUxMFpqZ0kKz24XB++ZHoKZvkBLsUQ2xfvi0KVOw62F
            CX0jMRkSxYeshEnXRjG6fHPizt/EsskWt+5DKvLeJ2liUIcOkuJYKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T12:39:42Z"
    mac: ENC[AES256_GCM,data:Jo+XE80NurgXyUmK/r3xoN01d6ULa4h7JCp3ZRwmsrKQzPaf0MSLDNkDNEahhblgkXX97HILvslL67YmzW1+7bbRonl1bY+KsTrjvLHTOTgw9iTlcrJIyjrz8cFTOOPNNhVxkQ2H1l68YW6ipnYBx40KUfsOgqpsAKY2r6KlqHg=,iv:FjLvB6HN4hu5zHQ3hrNJfOi6xkHHcZbgPPa3e5P+enc=,tag:Hiwcolq4l+KOsSmxpjIo7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
