apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:G/YxjdDWXUk7L6tN0zxZf0BMMJ0QgBJ+UkcjyqEcLz6FRGYtZT3nJxfgDsstJ/ta/I9LMCTTOCvZB2s2DbnpT0YR6yrN1uURpTg18aClbKANdsnpaaSm0jrvsdyWuPGLAUxuUjb+dV7lx18VC5ar3azAmZDJ3BZnxkzaZtdkW2STrjoWGzA95sbHCzjvoFG1rMaNjNQasm/YmgLqXKT9sodxZb3/AZBFJQVBtN4fxLg=,iv:A/YD8bPDUuxnpMCEfrsbLfIIxAPCV6aN25kgDOO9QOM=,tag:7QguVggGK52LxaTnJxADjA==,type:str]
sops:
    age:
        - recipient: age1yjgkfwawgzy5qf45jhjz4f49zjp0zntw6xj4mggw8ehjed0w9u2qxqahvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VURZZVpXMmZJOHo5UWNX
            bUc0TTU4ck5IOTBaNDJpdEIzQ0FkR3ZpZ0Q4CmZla1VNSS92VXVnS2o0eW1tSWY1
            SCtOUGFHZGgwalN5MEJjS0dYbUN2bjgKLS0tIDEzKy9pTnR2NUh5NVJOcElLc2F6
            QW5oTy84OEJIeFE5N1Q1VzUxMFpqZ0kKz24XB++ZHoKZvkBLsUQ2xfvi0KVOw62F
            CX0jMRkSxYeshEnXRjG6fHPizt/EsskWt+5DKvLeJ2liUIcOkuJYKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T12:24:01Z"
    mac: ENC[AES256_GCM,data:RtepaDQllHn7/NN7YJk89Hp3JxC8eNVOZRahh/JcKv1S+yDSmzmkpDZZ3OuPdmtfklukHjM3+cQTY5D0Ze6NxULrXzQpcj0YyXC6CpjgT6tSsM27li7qlB9pT04DdH/XdnwevZlWDraUx4VqfscGDtYqjinI8eH2d0qGpPe8chI=,iv:O1SZXIoEtDyMfT1MOYhwxkBhuDPmXN4M81Db6k6UdQU=,tag:yAM6N4Xh20NKR9mR5s90MA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
