---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-kingston
parameters:
  fstype: "zfs"
  poolname: "storage"
  shared: "yes"
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-torrent-pool
parameters:
  fstype: "zfs"
  poolname: "torrent_pool"
  shared: "yes"
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-seagate-barracuda-2tb-pool
parameters:
  poolname: "seagate_barracuda_2tb_pool"
  fstype: "zfs"
  shared: "yes"
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-pool-data
parameters:
  poolname: "pool_data"
  fstype: "zfs"
  shared: "yes"
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
