---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: []
    imagePullPolicy: IfNotPresent
    permittedHostDevices:
      pciHostDevices:
        # Kingston NV3 SNV3S1000G. Не путать с KC3000 (2646:5013), на котором пул ZFS storage.
        - pciVendorSelector: "2646:5025"
          resourceName: kubevirt.io/kingston-snv3s1000g
    smbios:
      sku: "TalosCloud"
      version: "v0.1.0"
      manufacturer: "Talos Virtualization"
      product: "talosvm"
      family: "ccio"
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  infra:
    replicas: 1
  workloadUpdateStrategy: {}
