---
# Source: scaphandre/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaphandre
  namespace: scaphandre
  labels:
    app.kubernetes.io/name: "scaphandre"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: scaphandre-0.1.0
---
# Source: scaphandre/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scaphandre
  labels:
    app.kubernetes.io/name: "scaphandre"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: scaphandre-0.1.0
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - scaphandre
  verbs:
  - "use"
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
---
# Source: scaphandre/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scaphandre
  labels:
    app.kubernetes.io/name: "scaphandre"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: scaphandre-0.1.0
subjects:
- kind: ServiceAccount
  name: scaphandre
  namespace: scaphandre
roleRef:
  kind: ClusterRole
  name: scaphandre
  apiGroup: rbac.authorization.k8s.io
---
# Source: scaphandre/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: scaphandre
  namespace: scaphandre
  labels:
    app.kubernetes.io/name: scaphandre
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 8080
    name: metrics
    targetPort: metrics
  selector:
    app.kubernetes.io/name: scaphandre
---
# Source: scaphandre/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scaphandre
  namespace: scaphandre
  labels:
    app.kubernetes.io/name: "scaphandre"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: scaphandre-0.1.0
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: scaphandre
  template:
    metadata:
      name: scaphandre
      labels:
        app.kubernetes.io/name: "scaphandre"
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: scaphandre-0.1.0
    spec:
      containers:
      - name:  scaphandre
        image: "hubblo/scaphandre:latest"
        args:
            - prometheus
            - --containers
        env:
        ports:
        - name: metrics
          containerPort: 8080
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 75m
            memory: 100Mi
        volumeMounts:
        - mountPath: /proc
          name: proc
          readOnly: false
        - mountPath: /sys/class/powercap
          name: powercap
          readOnly: false
      securityContext:
        runAsUser: 0
        runAsGroup: 
      serviceAccountName: scaphandre
      tolerations:
      # Tolerate all taints for observability
      - operator: "Exists"
      volumes:
      - hostPath:
          path: /proc
          type: "Directory"
        name: proc
      - hostPath:
          path: /sys/class/powercap
          type: "Directory"
        name: powercap
