apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cert-manager-webhook-cloudns-api-secret
stringData:
    auth_id: ENC[AES256_GCM,data:SrSPlnk=,iv:bHqsBIo2dnJhKQr9OSP0/e4yw5cIFMhqcMnB7/QbzJ8=,tag:CE071hh/qxA/e4F4kv4deQ==,type:str]
    auth_password: ENC[AES256_GCM,data:ZeqpUKlBTsWvqSmh5MJ/Fu2duG3bXBcB/G9+9U2/WpVpKq17NsTtCw==,iv:f1PG8DvDQMNuG2Y+NGs4pXRv933hfXAIAOYqSDSoUWs=,tag:HF8vcddhktgNU9quA5FSqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yjgkfwawgzy5qf45jhjz4f49zjp0zntw6xj4mggw8ehjed0w9u2qxqahvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMDNNZTZmR3VTNzFFMEVO
            L1ZPWERaaEJXREQwMXlacFpLZjlCWUYrcVJnCldFRXlpaE4yaUxUc1QvRmtJZEo4
            cHZsbTdZbVd2VmtoOFJIQzhDaHpXY28KLS0tIFpwMjBTZ1JLVHlBcWZTZkRBS2xP
            WDFaYytXRXprRDBwYTlmUjdoNi9qU0UK/aw99uC3YJIB+QaUAt55EiLp0K9Tda7M
            hUiyW/xMPLxzeCAd8lmLsn/pgwhVS/4dIxKVaS8iFNL6UL2Nt7prpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T02:51:37Z"
    mac: ENC[AES256_GCM,data:BDZNe8cF4Jxj5vdLOVYOSnVduikjgWv6n0c7/qRfcE2lNbjGwvhJ0iefoCxTRq+E3/35lXTUkKXYiynv6tJVDEejMwR1CD6hRbcHBDW1HL0d0ezEGFjj0BGIhLUEt6bHxDGk7D9NmitJV8ZUvFa8db0xnq0/hv5a6W0Lwu1FtnM=,iv:PlRWCszhz2fG/2QPLD/CxkcLE42AnpO61/aVsM3IBsQ=,tag:bjE+MCEEXGuoXkCsAS6Deg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
