apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:l2pzrlu7V2beb62bEDE3OwKmmhfYjXm1AlPQgzFAFUvCyYIjXV45ppuz/9sdtOpboirxm20=,iv:81xaW6crZq5kAFA0a56HP3m73QaUh9fQxEGrzqDDY7k=,tag:xFt4tuWW/MfmXFsDwDiYTQ==,type:str]
sops:
    age:
        - recipient: age1yjgkfwawgzy5qf45jhjz4f49zjp0zntw6xj4mggw8ehjed0w9u2qxqahvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVk9oOWovZW1zaTdEdXlU
            U0JsZ0JPd2NQanNkZVpFdm0vSzcxSVpqOGhzCmpPVUFhci9PbmZ4U3ZZbFBLV2VV
            bGVPMmhkNUdXbys4eDNTMGxXUFQwcGsKLS0tIHhFdHBaU0wwWVBtUHlBNS8rUlJQ
            TjdPbTBFQ1NUb0FpS0c2ZnhrYnNKZVEKRR50L8eU7oa2VO8qzLWjEevRlJ2+lMkv
            01XBKhHEs9yyaEa5w4UstnRr3zOKO6lIVf5zF00NX/mgHI5Ae5UFRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T13:23:43Z"
    mac: ENC[AES256_GCM,data:jTO53L9KMbfbMofRJVOQfSEkalPap5N4U8WETu5lLOyqWHb/CNAQLdDb02Bh/mMx0FOu4YolbCNlNnDyhfq5l4Lf97flRjUn38ldy3077dS/oxW1w+i/uqaheFfTFhuHTfu6L5n0SCBGNu3CKStou33bkDYeWM9gCRF9TSKWXkw=,iv:L+QI3ckEu+PJtCZjMXeV0HbAfdv7cSwOsPDFcEJUmBc=,tag:uhAGjdDY+b8bDLuvWyYi5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
