apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ev0XZFscvkFr8AZF8jTCBx1asKWPO4Y7ecNB0c4RCZPt8JeDnWml9w==,iv:rHMvYZMpDaFFbkgCMPSmcXNkCBcrU9zzXvY3jWjFJ+s=,tag:Y1ONbc5nfX1NoQizjKWlUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yjgkfwawgzy5qf45jhjz4f49zjp0zntw6xj4mggw8ehjed0w9u2qxqahvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVVBQMko3S1J6QXVSYmpa
            dEFORGxPdUNoMTY5MWV0d3NkR1hoODk0UWdjCkRPZEFMRWN3V1NmUStlYmJCY21y
            RVhuRWxPMFczaTFka3MxK1BSaFBpOWMKLS0tIFh6Y1F0TzI5QnNSbTdkZ25ENWV4
            TmNnN2M1MTcyaEFOL0ZYS01lcDczQTAKmIx3hVlc9GXNq8menm+Fow+HcITfgW1p
            z+bWWpL2BjXzVWRSe8DN5g0SYEIBZ7hYrSeXm7+AdZiIXanA9IFE6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T14:04:44Z"
    mac: ENC[AES256_GCM,data:9x+YfCk10Laqex95ZOi61qJIeZbQ7/dFLa9+LBbYg/jXu5OfhyymWCjhyK/FSu4u8P3zlmSwqZqZc3OLTElKpQSykgON6OnA9/26co2BqLWkXHJYaUHyEXHzXy6FGDJTZK38g/pihRKJ9GA+S7O8/15wOoijU+3zfo7wrW7p8lw=,iv:+5C3CgxaoLCMcQU/iV19DbhfsKEjDQ5LmxduPcRUCiw=,tag:AVvb9FOswHnGEN+wMgfEyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
