# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

clusterName: "home-kubernetes"
endpoint: https://192.168.88.202:6443

clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"

additionalApiServerCertSans: &sans
  - ""
  - "127.0.0.1"
additionalMachineCertSans: *sans

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "anaconda"
    ipAddress: "192.168.88.202"
    installDiskSelector:
      serial: "50026B76862410D9"
    # talosctl ls /lib/modules/6.12.18-talos/extras
    kernelModules:
      - name: zfs
      - name: intel_pmc_core
      # - name: it87
      #   parameters:
      #     - ignore_resource_conflict=1
      #     - force_id=0x8628
    # https://factory.talos.dev/?arch=amd64&cmdline-set=true&extensions=-&extensions=siderolabs%2Famdgpu&extensions=siderolabs%2Fi915&extensions=siderolabs%2Fintel-ucode&extensions=siderolabs%2Fzfs&platform=metal&target=metal&version=1.10.0
    talosImageURL: factory.talos.dev/installer/66f858dd8061486a2340a8b0f3519921198e2da3a7ab4f6f77e371c5ae823faf
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "18:c0:4d:e0:ab:b5"
        dhcp: false
        addresses:
          - "192.168.88.202/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.88.1"
        mtu: 1500
    schematic:
      customization:
        extraKernelArgs:
          # TODO: в идеале конечно не подавлять эти сообщения, но пока другого выхода нет
          - pci=noaer
        systemExtensions:
          officialExtensions:
            - siderolabs/amdgpu
            - siderolabs/i915
            - siderolabs/intel-ucode
            # - siderolabs/nut-client # TODO: включить, когда буду подключать UPS
            - siderolabs/zfs
    extraManifests:
      - "./patches/anaconda/volumeconfig.yaml"

# Global patches
patches:
  - "@./patches/global/cluster-discovery.yaml"
  - "@./patches/global/containerd.yaml"
  - "@./patches/global/disable-search-domain.yaml"
  - "@./patches/global/dns.yaml"
  - "@./patches/global/hostdns.yaml"
  - "@./patches/global/kubelet.yaml"
  - "@./patches/global/ntp.yaml"
  - "@./patches/global/openebs-local.yaml"
  - "@./patches/global/sysctl.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/api-access.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/disable-admission-controller.yaml"
    - "@./patches/controller/etcd.yaml"

