---
devices:
  - name: tun
    groups:
      - count: 1000
        paths:
          - path: /dev/net/tun

  - name: dri
    groups:
      - count: 1
        paths:
          - path: /dev/dri

  - name: input
    groups:
      - count: 1
        paths:
          - path: /dev/input
