---
devices:
  - name: tun
    groups:
      - count: 1000
        paths:
          - path: /dev/net/tun

  - name: dri
    groups:
      - count: 1
        paths:
          - path: /dev/dri

  - name: input
    groups:
      - count: 10
        paths:
          - path: /dev/input
  
  - name: tty
    groups:
    - paths:
      - limit: 10
        path: "/dev/tty0"
      - path: "/dev/tty[1-9]"

  - name: udev
    groups:
      - count: 1
        paths:
          - path: /run/udev/data
