---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "naiveproxy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naive
  template:
    metadata:
      labels:
        app: naive
    spec:
      containers:
      - name: naive
        image: pocat/naiveproxy:v150.0.7871.63-1@sha256:fc0f8766eaf95eb5720ca9e2b0874fee2010bf2022ed8b21df483b22a90d4d8b
        ports:
          - containerPort: 1080
          - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 1080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 1080
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
          - name: "naive"
            mountPath: "/etc/naiveproxy"
            readOnly: true
      volumes:
        - name: "naive"
          secret:
            secretName: "naive"
