apiVersion: v1
kind: Secret
metadata:
    name: naive
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:m+yyeDH3RG/tjjZ7ZmWJtFm7sM06Sn89Id7aegG/rGeDbXGT+2xF3zwvJ1S+tofTnmE9BuVgvBalR5iQoeExdbXYnH5/57h1ny4CaCtb2aCXR/0tFVlRWVpLyUB4a6Ck88Px98qQ1WpRHXMFKjL/TMG/fcmyrNHkjDv/Bd/A9VvqSyIcz6z7/jjtCRQmQAs5MZr2IiYot5JdMSVhuL4kbSzqZ21nMOthP1kbnto65YvF5C7I,iv:j4da380FdBN1os2s99Bvf6T7RV7AI/8rf0b8rKa+cFI=,tag:Fy5jJQ/yTIl5RzzMMHTAMg==,type:str]
sops:
    age:
        - recipient: age1yjgkfwawgzy5qf45jhjz4f49zjp0zntw6xj4mggw8ehjed0w9u2qxqahvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdVJoRm1LendyTEZ2amwz
            RHcyWFN2VExCQjQrNDJXSUdldFNEeWhrT2g4CjBoQkdjUDVYQ0drbUNkdW8xaWdO
            S3c5d3NpeHVTeHBGd3Y4RllHNzM1MkUKLS0tIGhBQ3RkeXFsVCtWTUNZR3RFMTJJ
            NVdqMHJodFUvcHgzeXFKajhjL1QvWnMKNTAXTjne5CJbf6uwxJy+sWKRUOcoWPLJ
            72xp1YuVEycWbaTjmn7RUoDET3YOqS1r43RZ4gQjqIVo304rQnLzag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T08:13:26Z"
    mac: ENC[AES256_GCM,data:YqLaUPUvKyyaWhqZWvJaxaCSKeSESLEo/8MOxi/01Oocqgt6Qc/GH3b0GY+iO/i6qNHEpSJfz2LcmYTvnUTWx1OE09XKZ4Lpj1B3joac9eCzATlJ4xYM1aZeUcI9Am/nkKT0IFj+s4hHwXXFd+oGHpxvCVprYLz0spmyUdXEWvs=,iv:Cf240CC30t5B0yBw6u4F74d76wqG/c4S1BkDtKE41a4=,tag:4ay4CGjPGzp0MTzcBqyHiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
