---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: "postgresql-qbittorrent"
spec:
  teamId: "qbittorrent"
  # Разрешил использование без SSL
  patroni:
      pg_hba:
        - host    all             all             0.0.0.0/0               md5
        - host    all             all             ::/0                    md5
        - local   all             all                                     trust
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 3072Mi
  volume:
    size: 5Gi
    storageClass: "openebs-seagate-barracuda-2tb-pool"
  numberOfInstances: 1
  users:
    postgres:
    - superuser
    - createdb
    qbittorrent: []
  databases:
    qbittorrent: qbittorrent
  postgresql:
    version: "17"
