---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: echo
spec:
  endpoints:
    - dnsName: echo.${SECRET_DOMAIN}
      recordTTL: 60
      recordType: A
      targets:
        - 10.0.0.1
