# Если не включается, то настраивай по статье:
# https://wiki.astralinux.ru/pages/viewpage.action?pageId=1212627
# talosctl debug docker.io/library/alpine:latest --args /bin/sh
# apk add ethtool
# ethtool enx18c04de0abb5
# ethtool -s enx18c04de0abb5 wol g
---
apiVersion: v1alpha1
kind: EthernetConfig
name: enx18c04de0abb5
wakeOnLan:
  # - phy
  # - unicast
  # - multicast
  # - broadcast
  - magic
